services:
  - type: web
    name: eliza-agents
    env: node
    buildCommand: |
      apt-get update && apt-get install -y opus-tools libopus-dev ffmpeg
      pnpm install
      pnpm build
    startCommand: cd agent && pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.9.0